# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

silent: true

tasks:
  build:
    desc: Builds the extension
    cmd: web-ext build -s src/ -a out/ -o

  validate:
    desc: Validates the extension
    cmd: web-ext lint -s src/

  format:
    desc: Formats Python code
    cmd: ruff format . --line-length 80

  lint:
    desc: Lints Python code
    cmd: ruff check .
